baseURL: https://alperkan.at/
title: Alper Kanat
theme: papermod
enableEmoji: true
enableGitInfo: true
enableRobotsTXT: true
googleAnalytics: null

defaultContentLanguage: tr
languages:
  tr:
    languageName: 🇹🇷
    contentDir: content/tr
    menu:
      main:
        - name: arşiv
          url: /arsiv
          weight: 1
        - name: etiketler
          url: /tags
          weight: 2
        - name: hakkımda
          url: /hakkimda
          weight: 4
        - name: notlarım
          url: https://github.com/tunix/notebook
          weight: 5
    params:
      description: Yazılım, kahve, bira ve hayata dair paylaşmak istediğim her şey...
      keywords:
        - alper
        - kanat
        - kişisel
        - günlük
        - blog
      homeInfoParams:
        title: Merhaba!
        Content: >
          Yazılım, kahve, bira ve hayata dair paylaşmak istediğim her şey...
    weight: 1
  en:
    languageName: 🇬🇧
    contentDir: content/en
    menu:
      main:
        - name: archives
          url: /archives
          weight: 1
        - name: tags
          url: /tags
          weight: 2
        - name: about
          url: /about
          weight: 4
        - name: notes
          url: https://github.com/tunix/notebook
          weight: 5
    params:
      description: My thoughts about software, coffee, beer and everything else...
      keywords:
        - alper
        - kanat
        - personal
        - blog
      homeInfoParams:
        title: Hey there!
        Content: >
          My thoughts about software, coffee, beer and everything else...
    weight: 2

permalinks:
  posts: /:year/:month/:filename/

minify:
  disableJSON: true
  disableXML: true
  minifyOutput: true

params:
  env: production
  author: Alper Kanat
  description: Yazılım, kahve, bira ve hayata dair paylaşmak istediğim her şey...
  keywords:
    - alper
    - kanat
    - kişisel
    - günlük
    - blog

  defaultTheme: auto

  homeInfoParams:
    Title: Merhaba!
    Content: >
      Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
      tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim
      veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea
      commodo consequat. Duis aute irure dolor in reprehenderit in voluptate
      velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat
      cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id
      est laborum.

  socialIcons:
    - name: email
      url: mailto:me@alperkan.at
    - name: github
      url: https://github.com/tunix
    - name: gitlab
      url: https://gitlab.com/tunix
    - name: twitter
      url: https://twitter.com/tunix
    - name: instagram
      url: https://instagram.com/tunix
    - name: telegram
      url: https://t.me/alperkanat
    - name: linkedin
      url: https://www.linkedin.com/in/tunix

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  disableCodeCopy: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false
  displayFullLangName: true

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: /favicon.ico
    favicon16x16: /favicon.ico
    # favicon32x32: "<link / abs url>"
    apple_touch_icon: /favicon.ico
    # safari_pinned_tab: "<link / abs url>"

  label:
    text: Alper Kanat
    icon: /img/avatar.jpg
    iconHeight: 35

