baseURL = "https://alperkan.at/"
languageCode = "tr"
title = "Alper Kanat"
theme = "beautifulhugo"
enableEmoji = true
enableGitInfo = true
# googleAnalytics = ""

[Params]
  commit = "https://github.com/tunix/tunix.github.io/"
  rss = true
  readingTime = true
  logo = "img/avatar.jpg"
  hideAuthor = true

[Author]
  email = "me-@-alperkan.at"
  github = "tunix"
  gitlab = "tunix"
  twitter = "tunix"
  instagram = "tunix"
  telegram = "alperkanat"
  linkedin = "tunix"

[Permalinks]
  posts = "/:year/:month/:filename/"

[[menu.main]]
name = "hakkımda"
url = "/about"
weight = 1

[[menu.main]]
name = "notlarım"
url = "https://github.com/tunix/notebook"
weight = 2
