baseURL = "http://alperkan.at/"
languageCode = "tr-TR"
title = "Alper Kanat"
theme = "researcher"
enableEmoji = true
# googleAnalytics = ""

[params]
  author = "Alper Kanat"
  description = "Personal space of Alper Kanat"
  # [params.footer]
  #   text = "Alper Kanat"
  #   url = "https://github.com/tunix/alperkan.at"

[permalinks]
  "/" = "/:filename"

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/posts"
    weight = 1

  [[menu.main]]
    name = "Notebook"
    url = "https://github.com/tunix/notebook"
    weight = 2

  [[menu.main]]
    name = "twitter"
    url = "https://twitter.com/tunix"
    weight = 3

  [[menu.main]]
    name = "GitHub"
    url = "https://github.com/tunix"
    weight = 4

  [[menu.main]]
    name = "RSS"
    url = "/index.xml"
    post = "<img src='/img/rss-fill.svg' alt='RSS Feed' title='RSS Feed'>"
    weight = 4
