baseURL = "http://alperkan.at/"
languageCode = "tr-TR"
title = "Alper Kanat"
theme = "researcher"
enableEmoji = true
# googleAnalytics = ""

[params]
  author = "Alper Kanat"
  description = "Personal space of Alper Kanat"
  # [params.footer]
  #   text = "Alper Kanat"
  #   url = "https://github.com/tunix/alperkan.at"

[permalinks]
  "/" = "/:filename"

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/posts"
    weight = 1

  [[menu.main]]
    name = "Notebook"
    url = "https://github.com/tunix/notebook"
    weight = 2

  [[menu.main]]
    name = "twitter"
    url = "https://twitter.com/tunix"
    weight = 3

  [[menu.main]]
    name = "GitHub"
    url = "https://github.com/tunix"
    weight = 4

  [[menu.main]]
    name = "RSS"
    url = "/index.xml"
    post = " <svg width='1em' height='1em' viewBox='0 0 16 16' class='bi bi-rss-fill align-text-bottom' fill='currentColor' xmlns='http://www.w3.org/2000/svg'><path fill-rule='evenodd' d='M2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2zm1.5 2.5a1 1 0 0 0 0 2 8 8 0 0 1 8 8 1 1 0 1 0 2 0c0-5.523-4.477-10-10-10zm0 4a1 1 0 0 0 0 2 4 4 0 0 1 4 4 1 1 0 1 0 2 0 6 6 0 0 0-6-6zm.5 7a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3z'/></svg>"
    weight = 4
