baseURL = "http://alperkan.at/"
languageCode = "tr-TR"
title = "Alper Kanat"
theme = "researcher"
enableEmoji = true

[params]
  author = "Alper Kanat"
  description = "Personal space of Alper Kanat"
  # favicon = "favicon.ico"
  # [params.footer]
  #   text = "Alper Kanat"
  #   url = "https://github.com/tunix/alperkan.at"

[permalinks]
  "/" = "/:filename"

[menu]
  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 1

  [[menu.main]]
    name = "Blog"
    url = "/posts"
    weight = 2

  [[menu.main]]
    name = "Notebook"
    url = "https://github.com/tunix/notebook"
    weight = 3
