baseURL: https://alperkan.at/
title: Alper Kanat
theme: papermod
enableEmoji: true
enableGitInfo: true
enableRobotsTXT: true
googleAnalytics: G-SDT9Y68PM3

defaultContentLanguage: en
languages:
  tr:
    languageName: 🇹🇷
    contentDir: content/tr
    menu:
      main:
        - name: arşiv
          url: /arsiv
          weight: 1
        - name: etiketler
          url: /tags
          weight: 2
        - name: hakkımda
          url: /hakkimda
          weight: 4
        - name: notlarım
          url: https://github.com/tunix/notebook
          weight: 5
    params:
      description: Yazılım, kahve, bira, bisiklet ve hayata dair paylaşmak istediğim her şey...
      keywords:
        - alper
        - kanat
        - kişisel
        - günlük
        - blog
      homeInfoParams:
        title: Merhaba! 👋
        Content: >
          [Yazılım](/tags/yazılım), [kahve](/tags/kahve), [ev biracılığı](/tags/bira), [bisiklet](/tags/bisiklet) ve 
          ilgi duyduğum, düşüncelerimi paylaşmak istediğim her konuda yazmaya çalıştığım siteme hoşgeldiniz.
    weight: 1
  en:
    languageName: 🇬🇧
    contentDir: content/en
    menu:
      main:
        - name: archives
          url: /archives
          weight: 1
        - name: tags
          url: /tags
          weight: 2
        - name: about
          url: /about
          weight: 4
        - name: notes
          url: https://github.com/tunix/notebook
          weight: 5
    params:
      description: My thoughts about software, coffee, home brewery, cycling and everything else...
      keywords:
        - alper
        - kanat
        - personal
        - blog
      homeInfoParams:
        title: Hey there! 👋
        Content: >
          Welcome to my web site where I write stuff I care about such as [software](/tags/software), 
          [coffee](/tags/coffee), [home brewery](/tags/beer), [cycling](/tags/cycling).
    weight: 2

permalinks:
  posts: /:year/:month/:slug/

minify:
  disableJSON: true
  disableXML: true
  minifyOutput: true
